# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef6a4828d0deca000c3d9aaa9c2bc408a6c8753db89b7118728f89b95e909d8e43dc62b0155582e7bb3ca7c8d93f955a9e004af3baf317c0d31e871dc7c0fdb

test:
  secret_key_base: 01b808dfd3c3d237bfe87c3a79886d53a83d22ff2520b6a6b21e6c3b84284658d7958e9d7097bb735bdc406f794c9434ce8fe3a3e734701a570de4de1e7e3f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
